### ISSUE TITLE
On-device inferencing on Different delegates like CPU,GPU

### ISSUE THREAD

**Issue by Vinaysukhesh98** [meta-llama/llama-stack-client-kotlin#14]
I have seen  your collaboration with executorch which is very insightful for enabling on device inferencing for cpu , was there any plan yo enable for **GPU and NPU backends**

**Comment by cmodi-meta** [comment]
Hi @Vinaysukhesh98! Thanks for your question. In addition to CPU (like how you mentioned), ExecuTorch does also support inferencing on Qualcomm and MediaTek NPU backends as well. You can find the instructions [here](https://github.com/pytorch/executorch/tree/main/examples/demo-apps/android/LlamaDemo#building-the-apk). 

You can build executorch.aar specific for [Qualcomm NPU](https://github.com/pytorch/executorch/blob/main/examples/demo-apps/android/LlamaDemo/docs/delegates/qualcomm_README.md#build-aar-library) and [MediaTek NPU](https://github.com/pytorch/executorch/blob/main/examples/demo-apps/android/LlamaDemo/docs/delegates/mediatek_README.md#build-aar-library). (Note the prerequisites in each of the READMEs). Technically you can give this a try with some tweaks to include the backend type in the Android app (some code is already there) but we do plan on officially including the backend support in the Android app soon!

**Comment by cmodi-meta** [comment]
Closing for now but please let us know if you have any additional questions!
