### ISSUE TITLE
Where is this published? 

### ISSUE THREAD

**Issue by natanfudge** [meta-llama/llama-stack-client-kotlin#3]
There's no `"com.llama_stack_client.api:llama-stack-client-kotlin:0.0.1-alpha.0"` on maven central.

**Comment by Riandy** [comment]
Hi Natan, the SDK is not available in Maven yet.

For now, you can manually build the jars via the following command

```
export SKIP_MOCK_TESTS=true
./gradlew build 
```

We have updated the readme on more detailed instructions on how to build those libs

**Comment by natanfudge** [comment]
Hey Riandy, thank you for the instructions. 
I hope the SDK will be made available on maven ASAP, even as a beta artifact, as building from source on every update is troublesome.

**Comment by Riandy** [comment]
Great news, the Kotlin SDK is now also made available via maven central

implementation("com.llama.llamastack:llama-stack-client-kotlin:0.0.1-alpha.1")
